import pandas as pd
S_E = pd.read_csv('covid-stringency-index.csv')
E_U = pd.read_csv('states.csv')
COVID_DATA = pd.read_csv('transformed_data.csv')
#print(S_E.head(5))
#print(E_U.head(10))
#for val in S_E :
#    print(val)
#print(S_E.head(3))
#print(S_E.info())
#print(S_E.describe())

#print(S_E.shape)
#print(S_E.columns)
#print(E_U.columns)
print(COVID_DATA.columns)
#print(S_E.index)
#print(E_U.index)
#EU=(pd.concat([S_E, E_U], sort=True))
#print(EU.head(5))
#print(EU.columns)

EU2=(S_E.merge(E_U, left_on='Entity', right_on='Country', how='outer'))
print(EU2.head(10))
print(EU2.columns)
COVID_EU2=(EU2.merge(COVID_DATA, left_on='Code', right_on='CODE', how='outer'))
print(COVID_EU2.head(10))
print(COVID_EU2.columns)